apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: digisense-microservices
  nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
        - path: /admin/*
          backend:
            serviceName: admin-portal-svc
            servicePort: 8001
        - path: /webapi/*
          backend:
            serviceName: webapi-svc
            servicePort: 8001